# Generated by Django 4.2.16 on 2024-12-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iaitem',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
